# code /home/gitpod/.dbt/profiles.yml
# profiles.yml
# This file should be placed in ~/.dbt/ directory, but for Replit we'll keep it in the project root
dbtbasic:
  outputs:
    dev:
      type: sqlite
      database: 'dbtbasic.db'
      schema: 'main'
      schema_directory: '.'
      schemas_and_paths:
        main: 'dbtbasic.db'
      # SQLite configuration for dbt-sqlite adapter
      threads: 1
      keepalives_idle: 0
  target: dev
